#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -layout fr &

bspc monitor -d A B C D E

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "jetbrains-clion"  desktop='^1'
bspc rule -a "firefox"          desktop='^2'
bspc rule -a "discord"          desktop='^3'
bspc rule -a "Slime Slaughter"  desktop='^1' state=floating center=true

# Start

amixer set 'Master' 0%

nitrogen --restore &
polybar &
picom &

# kitty
# firefox -safe-mode
